Capstone Project (Course Planner V2)/Course-Planner-v2-project-development/CoursePlanner/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using CoursePlanner.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using CoursePlanner.Managers;
using Google.Apis.Auth;

namespace CoursePlanner.Controllers
{
    // all api calls regarding admin functions are here
    // incomplete as of now since we didn't implement admin functions
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        public AdminController(ILogger<AdminController> logger)
        {
            _logger = logger;
        }
        [Authorize]
        public IActionResult adminHome()
        {
            var authwait = HttpContext.AuthenticateAsync();
            authwait.Wait();
            AuthenticateResult auth = authwait.Result;
            // Get the idToken
            string idToken = auth.Properties.GetTokenValue(OpenIdConnectParameterNames.IdToken);
            var payloadwait = GoogleJsonWebSignature.ValidateAsync(idToken);
            payloadwait.Wait();
            var payload = payloadwait.Result;
            string miamiID = UserController.GetMiamiID(payload);
            if (!PersonManager.GetPerson(miamiID).IsAdmin)
            {
                return Unauthorized();
            }
            ViewData["isAdmin"] = true;
            return View();

        }
        [Authorize]
        public IActionResult adminCourseAdd()
        {
            var authwait = HttpContext.AuthenticateAsync();
            authwait.Wait();
            AuthenticateResult auth = authwait.Result;
            // Get the idToken
            string idToken = auth.Properties.GetTokenValue(OpenIdConnectParameterNames.IdToken);
            var payloadwait = GoogleJsonWebSignature.ValidateAsync(idToken);
            payloadwait.Wait();
            var payload = payloadwait.Result;
            string miamiID = UserController.GetMiamiID(payload);
            if (!PersonManager.GetPerson(miamiID).IsAdmin)
            {
                return Unauthorized();
            }
            ViewData["isAdmin"] = true;
            //This sends the url values(course info) into the adminManager
            AdminManager.AddCourse(HttpContext.Request.QueryString.ToString());
            //Read the course groups to put in html
            ViewData["groups"] = AdminManager.GetCourseGroupNames();
            ViewData["allcourses"] = AdminManager.GetAllCourses();
            ViewData["departments"] = AdminManager.GetAllDepartments();
            return View();
        }
    
        [Authorize]
        public IActionResult adminCourseUpdate()
        {
            var authwait = HttpContext.AuthenticateAsync();
            authwait.Wait();
            AuthenticateResult auth = authwait.Result;
            // Get the idToken
            string idToken = auth.Properties.GetTokenValue(OpenIdConnectParameterNames.IdToken);
            var payloadwait = GoogleJsonWebSignature.ValidateAsync(idToken);
            payloadwait.Wait();
            var payload = payloadwait.Result;
            string miamiID = UserController.GetMiamiID(payload);
            if (!PersonManager.GetPerson(miamiID).IsAdmin)
            {
                return Unauthorized();
            }
            ViewData["isAdmin"] = true;
            AdminManager.UpdateCourse(HttpContext.Request.QueryString.ToString());
            ViewData["departments"] = AdminManager.GetAllDepartments();
            ViewData["allcourses"] = AdminManager.GetAllCourses();
            return View();
            
        }

        [Authorize]
        public IActionResult adminDeleteCourse()
        {
            var authwait = HttpContext.AuthenticateAsync();
            authwait.Wait();
            AuthenticateResult auth = authwait.Result;
            // Get the idToken
            string idToken = auth.Properties.GetTokenValue(OpenIdConnectParameterNames.IdToken);
            var payloadwait = GoogleJsonWebSignature.ValidateAsync(idToken);
            payloadwait.Wait();
            var payload = payloadwait.Result;
            string miamiID = UserController.GetMiamiID(payload);
            if (!PersonManager.GetPerson(miamiID).IsAdmin)
            {
                return Unauthorized();
            }
            ViewData["isAdmin"] = true;
            AdminManager.DeleteCourse(HttpContext.Request.QueryString.ToString());
            ViewData["allcourses"] = AdminManager.GetAllCourses();
            return View();
        }
        [ResponseCache(Duration = 0,
            Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            });
        }
    }
}

Capstone Project (Course Planner V2)/Course-Planner-v2-project-development/CoursePlanner/Controllers/PlanController.cs
using System.Diagnostics;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CoursePlanner.Models;
using Microsoft.AspNetCore.Http;
using CoursePlanner.Managers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using System.Threading.Tasks;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Google.Apis.Auth;

namespace CoursePlanner.Controllers
{
    public class PlanController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public PlanController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize]
        public async Task<IActionResult> EditPlanAsync(int planID)
        {
            // Get the authentication information 
            AuthenticateResult auth = await HttpContext.AuthenticateAsync();
            // Get the idToken
            string idToken = auth.Properties.GetTokenValue(OpenIdConnectParameterNames.IdToken);
            try
            {
                // Get the payload
                var payload = await GoogleJsonWebSignature.ValidateAsync(idToken);
                // Get the miamiID from the payload
                string miamiID = UserController.GetMiamiID(payload);
                // Set the miamiID
                ViewData["miamiID"] = miamiID;
                var personID = PersonManager.GetPersonID(miamiID);
                ViewData["isAdmin"] = PersonManager.GetPerson(miamiID).IsAdmin;
                // Check if miamiID owns this plan
                if (!PlanManager.PersonOwnsPlan(personID, planID))
                {
                    // Throw an exception
                    throw PlanManager.NotYourPlanIDException();
                }
            }
            catch
            {
                return BadRequest();
            }
            // Get the detailed plan
            var detailed = PlanManager.GetDetailedPlans(planID);
            // Store the plans in the dictionary
            var organized = new SortedDictionary<string,
                SortedDictionary<string, SemesterInfo>>();
            // Store all of the course IDs that are saved
            List<int> courses = new();
            // Iterate through all of the courses
            foreach(var detail in detailed)
            {
                // Get the current year
                var year = detail.CurrentYear;
                // Format the year as xxxx-xx (ex. 2020-21)
                var temp = year % 100;
                string formalYear = year / 100 + "-" + temp;
                if (detail.Season == "Completed")
                {
                    ViewData["CompSemID"] = detail.SemesterID;
                    formalYear = "Completed";
                }
                // Get the current model in that year, or
                // create a new dictionary
                SortedDictionary<string, SemesterInfo> plans =
                    organized.GetValueOrDefault(formalYear, new SortedDictionary<string,
                    SemesterInfo>());
                // Check if the season (fall, spring, ...) exists
                if (plans.ContainsKey(detail.Season))
                {
                    // Add the plan to the existing model
                    plans[detail.Season].Plan.AddPlan(detail);
                }
                else
                {
                    // Create a new model
                    var plan = new SemesterInfo();
                    // Add the information to the course 
                    plan.Plan.AddPlan(detail);
                    // Set the semester ID
                    plan.SemesterID = detail.SemesterID;
                    // Add the model to the dictionary
                    plans.Add(detail.Season, plan);
                }
                // Add the course to the total course list
                var course = detail.ToCourse();
                courses.Add(course.Course.CourseID);
                // Add the dictionary to the organized dictionary
                organized[formalYear] = plans;
            }
            // Store the organized semesters in the view data
            ViewData["organized"] = organized;
            // Get the comments and store it in the viewdata
            ViewData["comments"] = new CommentModel(planID);
            // Store the planID
            ViewData["planID"] = planID;
            // Get the year information of the plan and add it to the ViewData
            int planYear = PlanManager.GetPlanYear(planID);
            var degreeID = PlanManager.GetDegreeID(planID);
             // Set the courses
            ViewData["courses"] = courses;
            // Get all of the groups
            SortedDictionary<CourseGroup, List<CourseDetail>> groups = new();
            foreach (var Cgroup in CourseManager.GetCourseGroups(degreeID, planYear))
            {
                // Get all of the courses for the group
                groups[Cgroup] = CourseManager.GetDetailedCousesForGroup(Cgroup.GroupID);
            }
            // Store the groups in the ViewData
            ViewData["groups"] = groups;
            return View();
        }

        /**
         * Method to return the view of create plan page.
         */
        [Authorize]
        public async Task<IActionResult> CreatePlanAsync()
        {
            // Get the authentication information 
            AuthenticateResult auth = await HttpContext.AuthenticateAsync();
            // Get the idToken
            string idToken = auth.Properties.GetTokenValue(OpenIdConnectParameterNames.IdToken);
            try
            {
                // Get the payload
                var payload = await GoogleJsonWebSignature.ValidateAsync(idToken);
                // Get the miamiID from the payload
                string miamiID = UserController.GetMiamiID(payload);
                PersonManager.GetPersonID(miamiID);
                ViewData["isAdmin"] = PersonManager.GetPerson(miamiID).IsAdmin;
                // Set the miamiID
                ViewData["miamiID"] = miamiID;
                ViewData["title"] = "Create Plan";
                ViewData["pageTitle"] = "Create a Plan";
                ViewData["years"] = GetYears();
                ViewData["degrees"] = DegreeManager.GetAllDegrees();
                return View();
            }
            catch
            {
                return BadRequest();
            }
        }

        /**
         * Helper method to get the previous ten years as an array,
         * counting from current year.
         */
        private int[] GetYears()
        {
            int[] years = new int[10];
            int currentYear = System.DateTime.Now.Year;

            for(int i = 0; i < 10; i++)
            {
                years[i] = currentYear - i;
            }

            return years;
        }

        /**
         * Method to return the view of select plan page.
         * The miami ID here is just a placeholder, it should be replaced with logged in user's miami ID 
         * later when CAS login is implemented. 
         */
        public async Task<IActionResult> SelectPlan()
        {
            // Get the authentication information 
            AuthenticateResult auth = await HttpContext.AuthenticateAsync();
            // Get the idToken
            string idToken = auth.Properties.GetTokenValue(OpenIdConnectParameterNames.IdToken);
            try
            {
                // Get the payload
                var payload = await GoogleJsonWebSignature.ValidateAsync(idToken);
                // Get the miamiID from the payload
                string miamiID = UserController.GetMiamiID(payload);
                PersonManager.GetPersonID(miamiID);
                // Set the miamiID
                ViewData["miamiID"] = miamiID;
                ViewData["plans"] = PlanManager.GetPlanDetails(miamiID);
                ViewData["title"] = "Select Plan";
                ViewData["pageTitle"] = "Select a Plan";
                ViewData["isAdmin"] = PersonManager.GetPerson(miamiID).IsAdmin;
                return View();
            }
            catch
            {
                return BadRequest();
            }
        }

        /**
         * Method to delete a plan and redirect to select plan page.
         */
        [Authorize]
        public async Task<IActionResult> DeletePlanAsync(int planID)
        {
            // Get the authentication information 
            AuthenticateResult auth = await HttpContext.AuthenticateAsync();
            // Get the idToken
            string idToken = auth.Properties.GetTokenValue(OpenIdConnectParameterNames.IdToken);
            try
            {
                // Get the payload
                var payload = await GoogleJsonWebSignature.ValidateAsync(idToken);
                // Get the miamiID from the payload
                string miamiID = UserController.GetMiamiID(payload);
                int personID = PersonManager.GetPersonID(miamiID);
                if (PlanManager.PersonOwnsPlan(personID, planID))
                {
                    PlanManager.DeletePlan(planID);
                    return RedirectToAction("SelectPlan");
                } else
                {
                    throw PlanManager.NotYourPlanIDException();
                }
            }
            catch
            {
                return BadRequest();
            }
        }

        [ResponseCache(Duration = 0,
            Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ??
                    HttpContext.TraceIdentifier
            });
        }

        public IActionResult Home()
        {
            return View();
        }
    }
}

Capstone Project (Course Planner V2)/Course-Planner-v2-project-development/CoursePlanner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["title"] - CoursePlanner</title>
    @RenderSection("head", required: false)
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <style>
        .dropbtn {
            background-color: #c3142d;
            color: white;
            padding: 16px;
            font-size: 16px;
            border: none;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f1f1f1;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

                .dropdown-content a:hover {
                    background-color: #c3142d;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .dropdown:hover .dropbtn {
            background-color: black;
        }

        body {
            height: 800px;
            background-image: url('https://ceclnx01.cec.miamioh.edu/~crailjc/images/BentonFinal.png');
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            position: relative;
            background-attachment: fixed;
            margin: 0;
            padding: 0;
        }
        .navbar .nav-item:not(:last-child) {
          margin-right: 35px;
        }
        .dropdown-menu {
            margin: 0;
        }
        .dropdown-toggle::after {
           transition: transform 0.15s linear; 
        }
 
        .show.dropdown .dropdown-toggle::after {
          transform: translateY(3px);
        }
    </style>
</head>




<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#c3142d;">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">CoursePlanner</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Plan" asp-action="CreatePlan">Create Plan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Plan" asp-action="SelectPlan">Select Plan</a>
                        </li>
                        @if (ViewData["isAdmin"] != null && (bool)ViewData["isAdmin"])
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" style="color:white" aria-expanded="false">
                                    Admin Tools
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Admin" asp-action="adminHome">Admin Home</a>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Admin" asp-action="adminCourseAdd">Add Course</a>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Admin" asp-action="adminCourseUpdate">Update Course</a>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Admin" asp-action="adminDeleteCourse">Delete Course</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid" id="pageContainer">
        <h1 class="display-4 text-center">@ViewData["pageTitle"]</h1>
        <main role="main">
            @RenderBody()
        </main>
    </div> 
    <footer class="page-footer border-top footer text-muted text-center mt-auto" style="background-color:white; position: fixed;">
     <div class="container">
            &copy; 2021 - CoursePlanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
     </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        const $dropdown = $(".dropdown");
        const $dropdownToggle = $(".dropdown-toggle");
        const $dropdownMenu = $(".dropdown-menu");
        const showClass = "show";
     $dropdown.hover(
      function() {
        const $this = $(this);
        $this.addClass(showClass);
        $this.find($dropdownToggle).attr("aria-expanded", "true");
        $this.find($dropdownMenu).addClass(showClass);
      },
      function() {
        const $this = $(this);
        $this.removeClass(showClass);
        $this.find($dropdownToggle).attr("aria-expanded", "false");
        $this.find($dropdownMenu).removeClass(showClass);
      }
    );
    </script>
</body>
</html>